### PR TITLE
Ds dashboard feature

### PR DESCRIPTION
**Pull request by ParaSwarm**
Merge of Dashboard changes - new RadCalendar and addition of Mock Workouts and Meal Plans to calendar view.

### CODE REVIEW

**Comment by symbyte** [comment]
By Zeus' great, flowing beard! I shall inspect this immediately!

**Comment by symbyte** [comment]
For some reason, the calendar UI event popups stay active even when navigating to other fragments or pressing the back button. Is there maybe a way to make those no longer display when the fragment is paused/destroyed?

**Comment by symbyte** [comment]
Something else weird I noticed: if you have an active pop up and navigate away from the dashboard, and then come back and click on a different day to generate a different pop up, the previous one remains as well as displaying the new one

**Comment by ParaSwarm** [comment]
Utterly dreadful. I'll checks it out soon

**Comment by symbyte** [comment]
Ok, let me know if it's a quick easy fix.

If it isn't, this seems like the sort of bug I can navigate around to avoid showing it in the demo, so we could just merge it if this is that case and figure it out next sprint

**Pull request merged**
